var quiz = new Array(); var r = 0;
var resPage = 'SortingQuiz';
quiz[r++] =('What are you most looking forward to learning at Hogwarts?~Flying on a broomstick<img src="images/20-3.png" /><img src="images/Seperator.png"/>~All about magical creatures, and how to care for them<img src="images/20-5.png" /><img src="images/Seperator.png"/>~Apparition and Disapparition (being able to materialize and dematerialize at will)<img src="images/20-1.png" /><img src="images/Seperator.png"/>~Hexes and Jinxes<img src="images/20-4.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Which of the following would you most hate people to call you?~Cowardly<img src="images/1-3.png" /><img src="images/Seperator.png"/>~Selfish<img src="images/1-4.png" /><img src="images/Seperator.png"/>~Ignorant<img src="images/1-2.png" /><img src="images/Seperator.png"/>~Ordinary<img src="images/1-1.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Four boxes are placed before you. Which would you try and open~The small tortoiseshell box, embellished with gold, inside which some small creatures seems to be squeaking.<img src="images/18-1.png" /><img src="images/Seperator.png"/>~The small pewter box, unassuming and plain, with a scratched message upon it that reads \'I ONLY OPEN FOR THE WORTHY\'<img src="images/18-4.png" /><img src="images/Seperator.png"/>~The ornate golden casket, standing on clawed feet, whose inscription warns that both secret knowledge and unbearable temptation lie within.<img src="images/18-3.png" /><img src="images/Seperator.png"/>~The gleaming jet black box with a silver lock and key, marked with a mysterious rune that you know to be the mark of Merlin.<img src="images/18-2.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Which of the following would you most like to study?~Werewolves<img src="images/7-6.png" /><img src="images/Seperator.png"/>~Merpeople<img src="images/7-3.png" /><img src="images/Seperator.png"/>~Ghost<img src="images/7-4.png" /><img src="images/Seperator.png"/>~Vampires<img src="images/7-5.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Given the choice, would you rather invent a potion that would guarantee you:~Glory<img src="images/3-2.png" /><img src="images/Seperator.png"/>~Love<img src="images/3-1.png" /><img src="images/Seperator.png"/>~Wisdom<img src="images/3-3.png" /><img src="images/Seperator.png"/>~Power<img src="images/3-4.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('After you have died, what would you most like people to do when they hear your name?~Ask for more stories about your adventures.<img src="images/4-3.png" /><img src="images/Seperator.png"/>~Miss you and smile.<img src="images/4-1.png" /><img src="images/Seperator.png"/>~Think in admiration of your achievements.<img src="images/4-2.png" /><img src="images/Seperator.png"/>~I don\'t care what people think of me when I\'m dead, it\'s when I\'m alive that matters.<img src="images/4-4.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Which would you rather be?~Imitated<img src="images/21-2.png" /><img src="images/Seperator.png"/>~Trusted<img src="images/21-3.png" /><img src="images/Seperator.png"/>~Praised<img src="images/21-4.png" /><img src="images/Seperator.png"/>~Envied<img src="images/21-1.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Late at night, walking alone down the street, you hear a peculiar cry that you believe to have a magical source. Do you:~Draw your wand and stand your ground?<img src="images/8-3.png" /><img src="images/Seperator.png"/>~Draw your wand and try to discover the source of the noise?<img src="images/8-2.png" /><img src="images/Seperator.png"/>~Proceed with caution, keeping one hand in your concealed wand and an eye out for any disturbance?<img src="images/8-1.png" /><img src="images/Seperator.png"/>~Withdraw into the shadows to await developments, while mentally reviewing the most appropriate defense spells?<img src="images/8-4.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('Which road tempts you most?~The twisting, leaf-strewn path through the woods<img src="images/25-3.png" /><img src="images/Seperator.png"/>~The wide, sunny, grassy lane<img src="images/25-1.png" /><img src="images/Seperator.png"/>~The cobbled street lined with ancient buildings<img src="images/25-4.png" /><img src="images/Seperator.png"/>~The narrow, dark, lateen-lit alley<img src="images/25-2.png" /><img src="images/Seperator.png"/>~~');
quiz[r++] =('A Muggle confronts you and says that they are sure you are a witch or wizard. Do you:~Ask what what makes them think so?<img src="images/19-1.png" /><img src="images/Seperator.png"/>~Tell them that you are worried about their mental health, and offer to call a doctor?<img src="images/19-4.png" /><img src="images/Seperator.png"/>~Agree, and walk away, leaving them to wonder whether you are bluffing?<img src="images/19-3.png" /><img src="images/Seperator.png"/>~Agree, and ask whether they\'d like a free sample of a jinx?<img src="images/19-2.png" /><img src="images/Seperator.png"/>~~');


